# docker-compose.prod.yml - Production deployment with Nginx + SSL
version: '3.8'

services:
  # Next.js application
  web:
    build: .
    environment:
      - NODE_ENV=production
      - DATABASE_URL=sqlite:./data/bookings.db
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_APP_PASSWORD=${EMAIL_APP_PASSWORD}
      - EMAIL_FROM=${EMAIL_FROM}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_LOGIN=${ADMIN_LOGIN}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}
      - AUTH_SECRET=${AUTH_SECRET}
      - NEXT_PUBLIC_BASE_URL=${NEXT_PUBLIC_BASE_URL}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - drum-network
    # Don't expose port 3000 externally - only for nginx

  # Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"     # HTTP port
      - "443:443"   # HTTPS port
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - drum-network

volumes:
  web_data:

networks:
  drum-network:
    driver: bridge